### ISSUE TITLE
Use this for c/cpp?

### ISSUE THREAD

**Issue by gareth-ib** [isukces/cs2php#10]
Can this be used for CPP as well? Or if you're bored and wanna port a version to do that? :)
thanks either way!

**Comment by isukces** [comment]
This project is designed only for C# language. 
C and C++ is not supported and there is no plan to ever support.
Major reason is that  Cs2PHP uses Roslyn that supports C# and Visual Basic, not C/C++.

Few weeks ago I started alternative project [C# to Python](https://github.com/isukces/cs2python) also based on Roslyn.
