### ISSUE TITLE
Generic Return Type

### ISSUE THREAD

**Issue by aersamkull** [isukces/cs2php#2]
At first, that you for sharing this already quite good compiler! I think it has a lot of potential! 

Meanwhile, it seems that a generic return type of a function seems to crash the compiler... In addition, both, System.Byte and System.UInt64 do not seems to work so far

**Comment by isukces** [comment]
Can you send some code example for this issue?

**Comment by aersamkull** [comment]
I think, I have done something like this:
```c# 
public static T Test<T>() where T: new()
{
      return new T();
}
```
Hope this helps :)

**Comment by isukces** [comment]
I have no idea how to implement this at this moment. We can use PHP construction like this:
$class = "MyClassName";
$object = new $class();
But class names are not the same in C# and PHP (i.e. DateTimeOffset in c#). Probably it's possible to implement this for user classes only (not for .NET framework classes).
